# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf6c18fd09e60e61561d0ebbf68aa42bb07d112ca0d6dfee4929fe6974d8faac0413d8b0610e251e658c314604c305f4b1e83d2d56e8d146e853c0c35b09f4f5

test:
  secret_key_base: d41daa716beb9c8e9b8f41eb4bf6c23f7a0eb6e84dc77421cd001a736cfb1c62f9c17841527c27f04c28984534d5866bbd96401dca0d8f1537cf9a0b7ded8b9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
